#include "text.hpp"

char const *
Text::s_text
= ("Lorem ipsum dolor sit amet, consectetur adipiscing elit"
   ", sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"
   ". Nulla pharetra diam sit amet nisl. Non arcu risus quis varius"
   ". Amet risus nullam eget felis eget nunc lobortis mattis"
   ". Maecenas accumsan lacus vel facilisis volutpat"
   ". At lectus urna duis convallis"
   ". Arcu felis bibendum ut tristique et egestas quis"
   ". Amet massa vitae tortor condimentum lacinia quis vel"
   ". Auctor eu augue ut lectus arcu bibendum"
   ". Sit amet nulla facilisi morbi tempus iaculis urna"
   ". Netus et malesuada fames ac turpis egestas integer"
   ". Suspendisse interdum consectetur libero id faucibus nisl"
   ". Nunc consequat interdum varius sit amet mattis"
   ". Orci porta non pulvinar neque laoreet suspendisse"
   ". Adipiscing commodo elit at imperdiet dui"
   ".\n"
   "Proin sed libero enim sed faucibus turpis in eu"
   ". Sit amet venenatis urna cursus eget nunc scelerisque viverra"
   ". Fermentum iaculis eu non diam"
   ". Ullamcorper malesuada proin libero nunc consequat"
   ". Velit scelerisque in dictum non"
   ". In est ante in nibh mauris cursus mattis molestie"
   ". Suspendisse potenti nullam ac tortor vitae purus"
   ". Aliquet enim tortor at auctor urna nunc"
   ". Est sit amet facilisis magna etiam"
   ". Amet mauris commodo quis imperdiet massa tincidunt"
   ". Suscipit tellus mauris a diam maecenas"
   ". Dolor sit amet consectetur adipiscing"
   ". Quam pellentesque nec nam aliquam sem et"
   ". Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus"
   ".\n"
   "Pharetra massa massa ultricies mi quis hendrerit"
   ". Eget gravida cum sociis natoque penatibus et magnis"
   ". Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae"
   ". Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim"
   ". Mi sit amet mauris commodo"
   ". Venenatis urna cursus eget nunc scelerisque"
   ". Orci phasellus egestas tellus rutrum"
   ". Quis lectus nulla at volutpat diam"
   ". Hac habitasse platea dictumst quisque sagittis purus"
   ". Pellentesque id nibh tortor id aliquet"
   ". Diam maecenas sed enim ut sem viverra"
   ". Sapien nec sagittis aliquam malesuada bibendum arcu"
   ". Ipsum dolor sit amet consectetur adipiscing elit ut"
   ". Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt"
   ". Aenean euismod elementum nisi quis eleifend quam"
   ".\n"
   "Morbi tristique senectus et netus et"
   ". Luctus venenatis lectus magna fringilla urna porttitor rhoncus"
   ". Placerat vestibulum lectus mauris ultrices"
   ". Aliquam ultrices sagittis orci a scelerisque purus semper eget"
   ". Risus viverra adipiscing at in"
   ". Massa id neque aliquam vestibulum morbi"
   ". Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper"
   ". Neque convallis a cras semper"
   ". Amet facilisis magna etiam tempor"
   ". Donec et odio pellentesque diam"
   ". Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada"
   ". Mi tempus imperdiet nulla malesuada pellentesque elit"
   ". Integer eget aliquet nibh praesent tristique magna sit amet purus"
   ". Facilisi morbi tempus iaculis urna"
   ".\n"
   "Commodo elit at imperdiet dui"
   ". Urna nunc id cursus metus aliquam eleifend"
   ". Urna neque viverra justo nec"
   ". A arcu cursus vitae congue mauris"
   ". Duis ut diam quam nulla porttitor massa id neque aliquam"
   ". Mi eget mauris pharetra et"
   ". Faucibus interdum posuere lorem ipsum dolor sit amet consectetur"
   ". Vestibulum sed arcu non odio euismod lacinia"
   ". Aliquet porttitor lacus luctus accumsan"
   ". Urna nec tincidunt praesent semper feugiat nibh sed"
   ". Egestas integer eget aliquet nibh praesent tristique"
   ". Sed vulputate odio ut enim blandit volutpat maecenas"
   ". Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec"
   ". A cras semper auctor neque vitae tempus quam"
   ". Quis viverra nibh cras pulvinar mattis"
   ". Feugiat nisl pretium fusce id velit ut tortor pretium viverra"
   ". Lobortis elementum nibh tellus molestie"
   ". Pellentesque massa placerat duis ultricies lacus sed"
   ". Donec massa sapien faucibus et molestie ac feugiat sed lectus"
   ".\n"
   "Et netus et malesuada fames ac"
   ". Tempus urna et pharetra pharetra massa massa"
   ". Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla"
   ". Tortor consequat id porta nibh venenatis cras"
   ". Eleifend mi in nulla posuere sollicitudin"
   ". Nisi est sit amet facilisis magna etiam tempor"
   ". Leo integer malesuada nunc vel risus commodo viverra maecenas"
   ". Diam quis enim lobortis scelerisque"
   ". Et ligula ullamcorper malesuada proin libero nunc consequat interdum"
   ". Sed vulputate odio ut enim blandit"
   ". Purus non enim praesent elementum"
   ". Lacinia at quis risus sed vulputate odio ut enim"
   ". In nisl nisi scelerisque eu ultrices vitae auctor eu augue"
   ". Lorem ipsum dolor sit amet consectetur adipiscing elit"
   ". Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare"
   ". Mauris nunc congue nisi vitae suscipit tellus"
   ".\n"
   "Dapibus ultrices in iaculis nunc sed augue lacus viverra vitae"
   ". Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate"
   ". Tempor orci eu lobortis elementum nibh"
   ". Pretium viverra suspendisse potenti nullam ac"
   ". Ut placerat orci nulla pellentesque"
   ". Cum sociis natoque penatibus et magnis dis parturient montes"
   ". Amet nisl purus in mollis"
   ". Elementum eu facilisis sed odio"
   ". Id consectetur purus ut faucibus pulvinar elementum integer enim"
   ". Mauris pharetra et ultrices neque ornare aenean euismod"
   ". Porttitor eget dolor morbi non arcu risus"
   ". Elementum curabitur vitae nunc sed velit dignissim"
   ".\n"
   "Adipiscing bibendum est ultricies integer quis auctor"
   ". Sagittis purus sit amet volutpat"
   ". Massa vitae tortor condimentum lacinia quis"
   ". Gravida quis blandit turpis cursus"
   ". Sed vulputate odio ut enim blandit volutpat"
   ". Arcu vitae elementum curabitur vitae nunc sed velit dignissim sodales"
   ". Mattis pellentesque id nibh tortor"
   ". Tristique nulla aliquet enim tortor"
   ". Convallis posuere morbi leo urna molestie at elementum eu facilisis"
   ". Mi tempus imperdiet nulla malesuada"
   ". Cras sed felis eget velit aliquet sagittis id consectetur"
   ". Varius vel pharetra vel turpis nunc eget lorem dolor"
   ". Semper eget duis at tellus at urna condimentum mattis"
   ".\n"
   "Velit sed ullamcorper morbi tincidunt ornare massa eget"
   ". Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper"
   ". Ultrices dui sapien eget mi proin"
   ". Mi eget mauris pharetra et ultrices neque"
   ". Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh"
   ". Id aliquet risus feugiat in ante"
   ". Eu lobortis elementum nibh tellus molestie nunc non"
   ". Non odio euismod lacinia at quis risus sed"
   ". Quam adipiscing vitae proin sagittis nisl rhoncus"
   ". Nunc id cursus metus aliquam eleifend mi"
   ". Fermentum posuere urna nec tincidunt praesent semper feugiat nibh"
   ". Non nisi est sit amet facilisis magna etiam tempor"
   ".\n"
   "Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus"
   ". Integer vitae justo eget magna"
   ". Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae"
   ". Eget nulla facilisi etiam dignissim diam"
   ". Turpis egestas maecenas pharetra convallis posuere morbi"
   ". Proin fermentum leo vel orci porta non pulvinar"
   ". Orci eu lobortis elementum nibh tellus molestie"
   ". Ipsum consequat nisl vel pretium"
   ". Elementum facilisis leo vel fringilla est"
   ". Eros in cursus turpis massa tincidunt dui ut"
   ". In arcu cursus euismod quis viverra"
   "!\n");
